### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Wenfengmi** [wangjiyuan9/WeatherDepth#1]
您好，请问能公布测试数据集吗

**Comment by wangjiyuan9** [comment]
Thank you for your interest in our work! We will release the dataset recently, and I think it will be around tomorrow. We are currently uploading them.
Also, we hope you can ask questions in English in the issue, which is one of the basic etiquette of GitHub :)

**Comment by wangjiyuan9** [comment]
I have released the WeatherKITTI dataset!

**Comment by wangjiyuan9** [comment]
I apologize for not uploading the correct KITTI GT file previously. I mistakenly uploaded the GT for the dense dataset instead. I can now assure you that the files are correct.

https://huggingface.co/datasets/exander/kitti-depth-gt/blob/main/gt_depths.npy is the test GT depth for KITTI.

https://huggingface.co/exander/D4RD/blob/main/gt_depths.npy is the GT depth for the Dense dataset.
