### ISSUE TITLE
provide a train and assessment

### ISSUE THREAD

**Issue by zjdaiyf** [wangjiyuan9/WeatherDepth#3]
Hello, thank you very much for your work, please can you provide a train and assessment？

**Comment by wangjiyuan9** [comment]
We have already provided the evaluation code.
For the training part, we will release it in a few days.

**Comment by zjdaiyf** [comment]
OK,Thank you!

**Comment by zjdaiyf** [comment]
Thank you for your work!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangjiyuan9/WeatherDepth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月27日(星期六) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangjiyuan9/WeatherDepth] provide a train and assessment (Issue #3)





 
Closed #3 as completed.

**Comment by wangjiyuan9** [comment]
We release the full training code!

**Comment by wangjiyuan9** [comment]
I have released the WeatherKITTI dataset!
