### ISSUE TITLE
WeatherKITTI Dataset and D4RD

### ISSUE THREAD

**Issue by zjdaiyf** [wangjiyuan9/WeatherDepth#4]
May I ask when your WeatherKITTI Dataset and another masterpiece D4RD code will be released？

**Comment by wangjiyuan9** [comment]
I'm sorry that I have participated in VALSE in China in the last week and didn't reply to you. WeatherKITTI Dataset will be released soon. D4RD code needs more time.

**Comment by wangjiyuan9** [comment]
We release the full training code!

**Comment by wangjiyuan9** [comment]
I have released the WeatherKITTI dataset!

**Comment by wangjiyuan9** [comment]
I apologize for not uploading the correct KITTI GT file previously. I mistakenly uploaded the GT for the dense dataset instead. I can now assure you that the files are correct.

https://huggingface.co/datasets/exander/kitti-depth-gt/blob/main/gt_depths.npy is the test GT depth for KITTI.

https://huggingface.co/exander/D4RD/blob/main/gt_depths.npy is the GT depth for the Dense dataset.
