### ISSUE TITLE
train datasets

### ISSUE THREAD

**Issue by Wenfengmi** [wangjiyuan9/WeatherDepth#7]
Dear Author,

I hope this message finds you well. I am attempting to reproduce the training process but am not entirely clear about the distribution of the dataset. Although the GitHub page shows the tree structure of the test dataset, it does not provide information about the training dataset. Could you please describe the distribution of the relevant adverse weather conditions within the training dataset? I look forward to your response.

Best regards.

**Comment by wangjiyuan9** [comment]
I have packaged them into zip and uploaded them to cloudy. Now I want to make a website to release them.

**Comment by wangjiyuan9** [comment]
I have released the WeatherKITTI dataset!
